"""
Script to add missing courses to the CourseCatalog database.
Run with: cd apps/api && poetry run python -m src.add_new_courses
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.database import SessionLocal, engine, Base
from src.models import Course, CourseLevel, Semester

NEW_COURSES = [
    # ========== Missing Bachelor Courses ==========
    {
        "id": "IN1140",
        "title": "Introduksjon til språkteknologi",
        "title_english": "Introduction to Language Technology",
        "description": "Emnet gir en innføring i språkteknologiske metoder og lingvistisk teori anvendt på databehandlingsproblemer. Studentene utforsker grunnleggende språkteknologiske oppgaver som tokenisering, n-grammodeller, tagging og klassifisering, og lærer å analysere språklige data på flere nivåer.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "bachelor", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Skriftlig digital eksamen, 4 timer", "teaching_form": "Forelesninger + gruppeøvelser",
    },
    {
        "id": "IN1160",
        "title": "Introduksjon til maskinlæring",
        "title_english": "Introduction to Machine Learning",
        "description": "Emnet gir grunnleggende kunnskap om maskinlæring og kunstig intelligens med praktiske anvendelser innen språkteknologi, bildebehandling og robotikk. Studentene lærer veiledet og ikke-veiledet læring med Python, samt eksperimentdesign og etiske vurderinger.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "bachelor", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Skriftlig digital eksamen, 4 timer", "teaching_form": "Forelesninger + seminargruppe + lab",
    },
    {
        "id": "IN2031",
        "title": "Prosjektoppgave i programmering",
        "title_english": "Programming Project",
        "description": "Studentene gjennomfører et større programmeringsprosjekt hvor de anvender kunnskap fra tidligere kurs i en praktisk kontekst. Fokus på samarbeid, prosjektstyring og kodekvalitet.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "bachelor", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Prosjektinnlevering", "teaching_form": "Veiledning + prosjektarbeid",
    },
    {
        "id": "IN2080",
        "title": "Beregninger og kompleksitet",
        "title_english": "Computability and Complexity",
        "description": "Emnet dekker fundamentale begreper innen beregningsteori og kompleksitetsteori. Studentene lærer om Turing-maskiner, beregnbarhet, NP-fullstendighet og reduksjoner.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "bachelor", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + øvelser",
    },
    {
        "id": "IN2100",
        "title": "Logikk for distribuerte systemer",
        "title_english": "Logic for Distributed Systems",
        "description": "Emnet gir en innføring i formell logikk med anvendelser for distribuerte systemer. Studentene lærer om proposisjonslogikk, predikatlogikk, temporal logikk og modellsjekking.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "bachelor", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + øvelser",
    },
    {
        "id": "IN2160",
        "title": "Probabilistisk maskinlæring",
        "title_english": "Probabilistic Machine Learning",
        "description": "Emnet gir en innføring i sannsynlighetsbaserte metoder for maskinlæring. Studentene lærer om bayesiansk statistikk, grafiske modeller og variasjonell inferens.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "bachelor", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + øvelser",
    },
    {
        "id": "IN3000",
        "title": "Operativsystemer",
        "title_english": "Operating Systems",
        "description": "Emnet gir en grundig innføring i operativsystemers oppbygning og virkemåte. Dekker prosesshåndtering, minnehåndtering, filsystemer, I/O-systemer og sikkerhet i operativsystemer.",
        "credits": 20, "department": "Institutt for informatikk",
        "level": "bachelor", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + lab",
    },
    {
        "id": "IN3010",
        "title": "Transformativt design",
        "title_english": "Transformative Design",
        "description": "Emnet utforsker designmetoder som tar sikte på å skape transformativ endring gjennom teknologi. Studentene arbeider med deltakende designprosesser og kritisk refleksjon.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "bachelor", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Prosjektoppgave", "teaching_form": "Forelesninger + workshops",
    },
    {
        "id": "IN3015",
        "title": "Ultralydavbildning",
        "title_english": "Ultrasound Imaging",
        "description": "Emnet gir en innføring i prinsippene bak ultralydavbildning og signalbehandlingsmetoder som brukes i medisinsk diagnostikk.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "bachelor", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + lab",
    },
    {
        "id": "IN3090",
        "title": "Prosjektoppgave i informatikk: Digital økonomi og ledelse",
        "title_english": "Project in Informatics: Digital Economy and Leadership",
        "description": "Prosjektbasert emne hvor studentene arbeider med problemstillinger knyttet til digital økonomi og teknologiledelse i samarbeid med eksterne partnere.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "bachelor", "semester": ["fall", "spring"], "language": "Norwegian",
        "exam_form": "Prosjektinnlevering", "teaching_form": "Veiledning + prosjektarbeid",
    },
    {
        "id": "IN3120",
        "title": "Søketeknologi",
        "title_english": "Search Technology",
        "description": "Emnet dekker prinsipper og teknikker for informasjonsgjenfinning og søkemotorteknologi. Inkluderer indeksering, rangering, relevans og evaluering av søkesystemer.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "bachelor", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + øvelser",
    },
    {
        "id": "IN3130",
        "title": "Algoritmer: Design og effektivitet",
        "title_english": "Algorithms: Design and Efficiency",
        "description": "Emnet dekker avanserte algoritmer og datastrukturer med fokus på design, analyse og effektivitet. Inkluderer grafalgoritmer, dynamisk programmering, grådige algoritmer og NP-komplethet.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "bachelor", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + øvelser",
    },
    {
        "id": "IN3140",
        "title": "Introduksjon til robotikk",
        "title_english": "Introduction to Robotics",
        "description": "Emnet gir en innføring i grunnleggende robotikk, inkludert kinematikk, dynamikk, sensorikk, planlegging og kontroll av robotsystemer.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "bachelor", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + lab",
    },
    {
        "id": "IN3160",
        "title": "Digital systemkonstruksjon",
        "title_english": "Digital System Design",
        "description": "Emnet dekker design og implementasjon av digitale systemer med FPGA-teknologi. Studentene lærer VHDL, digital logikkdesign og prototyping.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "bachelor", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + lab",
    },
    {
        "id": "IN3170",
        "title": "Microelectronics",
        "title_english": "Microelectronics",
        "description": "The course covers fundamentals of microelectronic circuit design including CMOS technology, transistor-level design, and analog circuit principles.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "bachelor", "semester": ["spring"], "language": "English",
        "exam_form": "Written exam", "teaching_form": "Lectures + lab",
    },
    {
        "id": "IN3190",
        "title": "Digital signalbehandling",
        "title_english": "Digital Signal Processing",
        "description": "Emnet dekker grunnleggende teori og metoder for digital signalbehandling. Inkluderer sampling, filtrering, Fourier-analyse og anvendelser.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "bachelor", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + øvelser",
    },
    {
        "id": "IN3200",
        "title": "High-Performance Computing and Numerical Projects",
        "title_english": "High-Performance Computing and Numerical Projects",
        "description": "The course covers high-performance computing techniques including parallelization, vectorization, and optimization of numerical algorithms using C++ and Python.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "bachelor", "semester": ["spring"], "language": "English",
        "exam_form": "Project + oral exam", "teaching_form": "Lectures + lab",
    },

    # ========== Masters IN4xxx ==========
    {
        "id": "IN4000",
        "title": "Operativsystemer",
        "title_english": "Operating Systems",
        "description": "Grundig innføring i operativsystemers oppbygning og virkemåte på masternivå. Dekker prosesshåndtering, minnehåndtering, filsystemer, I/O og sikkerhet.",
        "credits": 20, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + lab",
    },
    {
        "id": "IN4011",
        "title": "Transformativt design",
        "title_english": "Transformative Design",
        "description": "Utforsker designmetoder som tar sikte på å skape transformativ endring gjennom teknologi, med deltakende designprosesser og kritisk refleksjon.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Prosjektoppgave", "teaching_form": "Forelesninger + workshops",
    },
    {
        "id": "IN4015",
        "title": "Ultralydavbildning",
        "title_english": "Ultrasound Imaging",
        "description": "Prinsipper bak ultralydavbildning og signalbehandlingsmetoder brukt i medisinsk diagnostikk, på masternivå.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + lab",
    },
    {
        "id": "IN4020",
        "title": "Databasesystemer",
        "title_english": "Database Systems",
        "description": "Avansert emne i databasesystemer som dekker spørreoptimalisering, transaksjonsbehandling, distribuerte databaser og moderne databaseteknologier.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + øvelser",
    },
    {
        "id": "IN4030",
        "title": "Introduksjon til bioinformatikk",
        "title_english": "Introduction to Bioinformatics",
        "description": "Emnet gir en innføring i bioinformatikk med fokus på sekvensanalyse, genomikk og algoritmer for biologiske data.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + lab",
    },
    {
        "id": "IN4050",
        "title": "Introduksjon til kunstig intelligens og maskinlæring",
        "title_english": "Introduction to Artificial Intelligence and Machine Learning",
        "description": "Emnet dekker veiledet klassifikasjon basert på kunstige nevrale nettverk (dyp læring), ikke-veiledet læring (klyngeanalyse), regresjon, optimalisering og forsterkende læring, samt eksperimentdesign og etiske vurderinger.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "English",
        "exam_form": "Skriftlig digital eksamen, 4 timer", "teaching_form": "Forelesninger + gruppeøvelser",
    },
    {
        "id": "IN4060",
        "title": "Semantiske teknologier",
        "title_english": "Semantic Technologies",
        "description": "Emnet dekker semantiske webteknologier inkludert ontologier, RDF, OWL, SPARQL og kunnskapsgrafer.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + øvelser",
    },
    {
        "id": "IN4070",
        "title": "Logikk",
        "title_english": "Logic",
        "description": "Avansert emne i matematisk logikk med fokus på predikatlogikk, modellteori, bevisteori og anvendelser i informatikk.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + øvelser",
    },
    {
        "id": "IN4080",
        "title": "Natural Language Processing",
        "title_english": "Natural Language Processing",
        "description": "Comprehensive overview of modern NLP with emphasis on probabilistic and machine learning techniques. Covers information extraction, machine translation, question-answering, tagging, parsing, and named entity recognition.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "English",
        "exam_form": "Skriftlig digital eksamen, 4 timer", "teaching_form": "Forelesninger + lab",
    },
    {
        "id": "IN4120",
        "title": "Søketeknologi",
        "title_english": "Search Technology",
        "description": "Prinsipper og teknikker for informasjonsgjenfinning og søkemotorteknologi på masternivå. Inkluderer indeksering, rangering og evaluering.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + øvelser",
    },
    {
        "id": "IN4140",
        "title": "Introduksjon til robotikk",
        "title_english": "Introduction to Robotics",
        "description": "Grunnleggende robotikk på masternivå, inkludert kinematikk, dynamikk, sensorikk, planlegging og kontroll av robotsystemer.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + lab",
    },
    {
        "id": "IN4150",
        "title": "Digitale økosystemer",
        "title_english": "Digital Ecosystems",
        "description": "Emnet utforsker digitale plattformer, økosystemer og forretningsmodeller i den digitale økonomien.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Prosjektoppgave", "teaching_form": "Forelesninger + seminarer",
    },
    {
        "id": "IN4160",
        "title": "Digital systemkonstruksjon",
        "title_english": "Digital System Design",
        "description": "Design og implementasjon av digitale systemer med FPGA-teknologi på masternivå. VHDL, digital logikkdesign og prototyping.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + lab",
    },
    {
        "id": "IN4170",
        "title": "Microelectronics",
        "title_english": "Microelectronics",
        "description": "Fundamentals of microelectronic circuit design including CMOS technology, transistor-level design, and analog circuit principles at master level.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "English",
        "exam_form": "Written exam", "teaching_form": "Lectures + lab",
    },
    {
        "id": "IN4180",
        "title": "Cyber Operations",
        "title_english": "Cyber Operations",
        "description": "The course covers offensive and defensive cyber operations, including vulnerability analysis, penetration testing, and incident response.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "English",
        "exam_form": "Oral exam", "teaching_form": "Lectures + lab",
    },
    {
        "id": "IN4190",
        "title": "Digital signalbehandling",
        "title_english": "Digital Signal Processing",
        "description": "Grunnleggende teori og metoder for digital signalbehandling på masternivå. Sampling, filtrering, Fourier-analyse og anvendelser.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + øvelser",
    },
    {
        "id": "IN4200",
        "title": "High-Performance Computing and Numerical Projects",
        "title_english": "High-Performance Computing and Numerical Projects",
        "description": "High-performance computing techniques including parallelization, vectorization, and optimization of numerical algorithms using C++ and Python at master level.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "English",
        "exam_form": "Project + oral exam", "teaching_form": "Lectures + lab",
    },
    {
        "id": "IN4210",
        "title": "Network and Communications Security",
        "title_english": "Network and Communications Security",
        "description": "The course covers security aspects of network communications including encryption, authentication, network protocols, and security analysis.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "English",
        "exam_form": "Written exam + home exam", "teaching_form": "Lectures + exercises",
    },
    {
        "id": "IN4220",
        "title": "Å forstå bruk før bruk",
        "title_english": "Understanding Use Before Use",
        "description": "Emnet handler om metoder for å forstå bruksbehov og brukskontekst før utvikling av nye IT-systemer.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Prosjektoppgave", "teaching_form": "Forelesninger + workshops",
    },
    {
        "id": "IN4230",
        "title": "Nettverk",
        "title_english": "Computer Networks",
        "description": "Avansert emne i datanettverk som dekker nettverksprotokoller, rutingsalgoritmer, transportlag og nettverkssikkerhet.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + øvelser",
    },
    {
        "id": "IN4240",
        "title": "Testing av programvare",
        "title_english": "Software Testing",
        "description": "Emnet dekker metoder og teknikker for testing av programvare, inkludert enhetstesting, integrasjonstesting, systemtesting og testautomatisering.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + øvelser",
    },
    {
        "id": "IN4270",
        "title": "Digital Business Development",
        "title_english": "Digital Business Development",
        "description": "The course explores digital business models, innovation strategies, and how organizations can leverage digital technology for competitive advantage.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "English",
        "exam_form": "Project + presentation", "teaching_form": "Lectures + seminars",
    },
    {
        "id": "IN4310",
        "title": "Deep Learning for Image Analysis",
        "title_english": "Deep Learning for Image Analysis",
        "description": "Common methods in deep learning applied to image data, covering key algorithms and concepts for training neural networks. Emphasizes supervised learning, image classification, image segmentation and object detection.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "English",
        "exam_form": "Skriftlig eksamen, 4 timer", "teaching_form": "Forelesninger + øvelser",
    },
    {
        "id": "IN4330",
        "title": "Effektiv parallellprogrammering",
        "title_english": "Efficient Parallel Programming",
        "description": "Emnet dekker teknikker for effektiv parallellprogrammering på moderne flerkjerneprosessorer og akseleratorer.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + lab",
    },
    {
        "id": "IN4340",
        "title": "Deltakende kvalitative forskningsmetoder",
        "title_english": "Participatory Qualitative Research Methods",
        "description": "Emnet gir en innføring i deltakende kvalitative forskningsmetoder med fokus på feltarbeid, intervjuer og dataanalyse.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Hjemmeeksamen", "teaching_form": "Forelesninger + seminarer",
    },
    {
        "id": "IN4380",
        "title": "Digital Transformation of Healthcare",
        "title_english": "Digital Transformation of Healthcare",
        "description": "The course explores how digital technologies transform healthcare delivery, focusing on health informatics, electronic health records, and data-driven decision making.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "English",
        "exam_form": "Oral exam", "teaching_form": "Lectures + seminars",
    },

    # ========== Masters IN5xxx ==========
    {
        "id": "IN5000",
        "title": "Qualitative Research Methods",
        "title_english": "Qualitative Research Methods",
        "description": "The course provides an introduction to qualitative research methods including ethnography, interviews, and thematic analysis in information systems research.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "English",
        "exam_form": "Home exam", "teaching_form": "Lectures + seminars",
    },
    {
        "id": "IN5010",
        "title": "Design, Technology and Society",
        "title_english": "Design, Technology and Society",
        "description": "The course explores relationships between design, technology and society, including participatory design, responsible innovation, and critical perspectives on technology.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "English",
        "exam_form": "Home exam", "teaching_form": "Lectures + seminars",
    },
    {
        "id": "IN5020",
        "title": "Distribuerte systemer",
        "title_english": "Distributed Systems",
        "description": "Innføring i prinsipper og praksis for konstruksjon av distribuerte systemer. Dekker fundamentale modeller, distribuert mellomvare, konsensusalgoritmer og moderne utfordringer innen sky, multimedia og IoT.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Skriftlig eller muntlig eksamen", "teaching_form": "Forelesninger + øvelser",
    },
    {
        "id": "IN5031",
        "title": "Protokoller og AI for fremtidens Internet",
        "title_english": "Protocols and AI for Future Internet",
        "description": "Emnet dekker fremtidens internettprotokoller og bruk av AI-teknikker for nettverksoptimalisering og -styring.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + øvelser",
    },
    {
        "id": "IN5040",
        "title": "Advanced Database Systems for Big Data",
        "title_english": "Advanced Database Systems for Big Data",
        "description": "The course covers advanced database concepts for big data including distributed databases, NoSQL systems, stream processing, and data lake architectures.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "English",
        "exam_form": "Written exam", "teaching_form": "Lectures + exercises",
    },
    {
        "id": "IN5050",
        "title": "Programming heterogeneous multi-core architectures",
        "title_english": "Programming heterogeneous multi-core architectures",
        "description": "The course covers programming techniques for heterogeneous multi-core systems including GPUs, FPGAs, and specialized accelerators.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "English",
        "exam_form": "Written exam", "teaching_form": "Lectures + lab",
    },
    {
        "id": "IN5060",
        "title": "Kvantitativ ytelsesanalyse",
        "title_english": "Quantitative Performance Analysis",
        "description": "Emnet dekker metoder for kvantitativ analyse av datasystemers ytelse, inkludert køteori, simulering og benchmarking.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + øvelser",
    },
    {
        "id": "IN5070",
        "title": "The future internet protocols",
        "title_english": "The Future Internet Protocols",
        "description": "The course explores emerging internet protocols and architectures including software-defined networking, network function virtualization, and next-generation transport protocols.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "English",
        "exam_form": "Written exam", "teaching_form": "Lectures + seminars",
    },
    {
        "id": "IN5080",
        "title": "Sikkerhets- og risikostyring",
        "title_english": "Security and Risk Management",
        "description": "Emnet dekker metoder for sikkerhetsstyring og risikovurdering av IT-systemer, inkludert trusselvurdering, sikkerhetspolicyer og compliance.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + øvelser",
    },
    {
        "id": "IN5090",
        "title": "Health data and decision-making",
        "title_english": "Health data and decision-making",
        "description": "The course covers methods for utilizing health data in clinical decision-making, including data analysis, machine learning for healthcare, and ethical considerations.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "English",
        "exam_form": "Project + presentation", "teaching_form": "Lectures + seminars",
    },
    {
        "id": "IN5110",
        "title": "Specification and Verification of Parallel Systems",
        "title_english": "Specification and Verification of Parallel Systems",
        "description": "The course covers formal methods for specifying and verifying concurrent and parallel systems using process algebras, model checking, and temporal logics.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "English",
        "exam_form": "Written exam", "teaching_form": "Lectures + exercises",
    },
    {
        "id": "IN5120",
        "title": "Tangible interaction",
        "title_english": "Tangible Interaction",
        "description": "The course explores physical and tangible interaction design, including prototyping with electronics, sensors, and physical computing.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "English",
        "exam_form": "Project", "teaching_form": "Lectures + workshops",
    },
    {
        "id": "IN5130",
        "title": "Uangripelige IT-systemer",
        "title_english": "Resilient IT Systems",
        "description": "Emnet dekker design og drift av robuste IT-systemer som tåler feil, angrep og uforutsette hendelser.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + øvelser",
    },
    {
        "id": "IN5140",
        "title": "Smarte prosesser og smidige metoder i systemutvikling",
        "title_english": "Smart Processes and Agile Methods in Systems Development",
        "description": "Emnet dekker smidige utviklingsmetoder og prosessforbedring for IT-prosjekter, inkludert Scrum, Kanban og DevOps.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Prosjektoppgave", "teaching_form": "Forelesninger + seminarer",
    },
    {
        "id": "IN5150",
        "title": "Recent Advancements in Internet Protocols",
        "title_english": "Recent Advancements in Internet Protocols",
        "description": "The course covers the latest developments in internet protocols, standards, and network architectures.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "English",
        "exam_form": "Written exam", "teaching_form": "Lectures + seminars",
    },
    {
        "id": "IN5160",
        "title": "Digital Leadership",
        "title_english": "Digital Leadership",
        "description": "The course explores leadership challenges and strategies in digital transformation, including technology governance and organizational change.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "English",
        "exam_form": "Home exam", "teaching_form": "Lectures + seminars",
    },
    {
        "id": "IN5170",
        "title": "Modeller for parallellitet",
        "title_english": "Models of Concurrency",
        "description": "Emnet dekker formelle modeller for parallelle og samtidige systemer, inkludert prosessalgebraer, Petri-nett og kommuniserende sekvensielle prosesser.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + øvelser",
    },
    {
        "id": "IN5180",
        "title": "Analog Microelectronics Design",
        "title_english": "Analog Microelectronics Design",
        "description": "The course covers advanced analog CMOS circuit design including operational amplifiers, feedback systems, and noise analysis.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "English",
        "exam_form": "Written exam", "teaching_form": "Lectures + lab",
    },
    {
        "id": "IN5190",
        "title": "Design for Sustainability",
        "title_english": "Design for Sustainability",
        "description": "The course explores how design and technology can address sustainability challenges, including sustainable HCI and green IT.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "English",
        "exam_form": "Project", "teaching_form": "Lectures + workshops",
    },
    {
        "id": "IN5200",
        "title": "Avansert digital systemkonstruksjon",
        "title_english": "Advanced Digital System Design",
        "description": "Avanserte metoder for design av digitale systemer med FPGA og ASIC-teknologi.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + lab",
    },
    {
        "id": "IN5210",
        "title": "Information Systems",
        "title_english": "Information Systems",
        "description": "The course covers theories and methods in information systems research, including organizational implications of IT and design science.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "English",
        "exam_form": "Home exam", "teaching_form": "Lectures + seminars",
    },
    {
        "id": "IN5220",
        "title": "Advanced mixed-signal CMOS integrated circuit design",
        "title_english": "Advanced mixed-signal CMOS integrated circuit design",
        "description": "The course covers design of mixed-signal integrated circuits including data converters, PLLs, and signal conditioning circuits.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "English",
        "exam_form": "Written exam", "teaching_form": "Lectures + lab",
    },
    {
        "id": "IN5230",
        "title": "Elektrisk støy - beregning og mottiltak",
        "title_english": "Electrical Noise - Calculation and Countermeasures",
        "description": "Emnet dekker analyse og håndtering av elektrisk støy i elektroniske systemer og integrerte kretser.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + øvelser",
    },
    {
        "id": "IN5240",
        "title": "Design av CMOS RF-integrerte kretser",
        "title_english": "CMOS RF Integrated Circuit Design",
        "description": "Emnet dekker design av CMOS radiofrekvens-integrerte kretser for trådløse kommunikasjonssystemer.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + lab",
    },
    {
        "id": "IN5250",
        "title": "Seminar i aksjonsforskning",
        "title_english": "Seminar in Action Research",
        "description": "Emnet gir en innføring i aksjonsforskning som metodologi, med fokus på samarbeid mellom forskere og praktikere.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Prosjektoppgave", "teaching_form": "Seminarer",
    },
    {
        "id": "IN5260",
        "title": "Low Power IoT nodes",
        "title_english": "Low Power IoT Nodes",
        "description": "The course covers design of low-power IoT devices including energy harvesting, sensor interfaces, and wireless communication protocols.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "English",
        "exam_form": "Project + oral exam", "teaching_form": "Lectures + lab",
    },
    {
        "id": "IN5290",
        "title": "Ethical Hacking",
        "title_english": "Ethical Hacking",
        "description": "The course covers vulnerability and penetration testing essential to modern cybersecurity. Students learn to test IT system security by identifying and exploiting vulnerabilities, while understanding legal boundaries and using current tools and techniques.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "English",
        "exam_form": "Hjemmeeksamen + skriftlig eksamen", "teaching_form": "Forelesninger + øvelser",
    },
    {
        "id": "IN5310",
        "title": "Advanced Deep Learning for Image Analysis",
        "title_english": "Advanced Deep Learning for Image Analysis",
        "description": "Advanced course covering state-of-the-art deep learning techniques for image analysis including GANs, diffusion models, and self-supervised learning.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "English",
        "exam_form": "Written exam", "teaching_form": "Lectures + exercises",
    },
    {
        "id": "IN5320",
        "title": "Development in platform ecosystems",
        "title_english": "Development in Platform Ecosystems",
        "description": "The course explores software development practices in platform ecosystems, including API design, platform governance, and third-party development.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "English",
        "exam_form": "Home exam", "teaching_form": "Lectures + seminars",
    },
    {
        "id": "IN5340",
        "title": "Statistisk signalbehandling",
        "title_english": "Statistical Signal Processing",
        "description": "Emnet dekker statistiske metoder for signalbehandling inkludert estimering, deteksjon og adaptiv filtrering.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + øvelser",
    },
    {
        "id": "IN5350",
        "title": "Design av CMOS bildesensor",
        "title_english": "CMOS Image Sensor Design",
        "description": "Emnet dekker design av CMOS bildesensorer inkludert pikselalternativer, utlesningskretser og støyanalyse.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + lab",
    },
    {
        "id": "IN5370",
        "title": "IKT og Globale Ulikheter",
        "title_english": "ICT and Global Inequalities",
        "description": "Emnet utforsker forholdet mellom informasjonsteknologi og globale ulikheter, med fokus på digital inkludering og utvikling.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Hjemmeeksamen", "teaching_form": "Forelesninger + seminarer",
    },
    {
        "id": "IN5380",
        "title": "Kompilatorteknikk",
        "title_english": "Compiler Construction",
        "description": "Emnet dekker teori og praksis for konstruksjon av kompilatorer, inkludert leksikalsk analyse, parsing, semantisk analyse og kodegenerering.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Skriftlig eksamen", "teaching_form": "Forelesninger + øvelser",
    },
    {
        "id": "IN5390",
        "title": "ICT for Development: Building a Better World?",
        "title_english": "ICT for Development: Building a Better World?",
        "description": "The course critically examines the role of ICT in international development, exploring both opportunities and challenges of technology-driven development.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "English",
        "exam_form": "Home exam", "teaching_form": "Lectures + seminars",
    },
    {
        "id": "IN5410",
        "title": "Energiinformatikk",
        "title_english": "Energy Informatics",
        "description": "Emnet dekker bruk av informatikk og AI for optimalisering av energisystemer, inkludert smartnett og energieffektivisering.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Prosjektoppgave", "teaching_form": "Forelesninger + lab",
    },
    {
        "id": "IN5420",
        "title": "Distributed Blockchain Technologies",
        "title_english": "Distributed Blockchain Technologies",
        "description": "Research-oriented seminar exploring state-of-the-art advances, principles, and techniques in blockchain technology. Covers Bitcoin origins, storage technologies, consensus protocols, and security aspects.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "English",
        "exam_form": "Oral exam", "teaching_form": "Seminarer",
    },
    {
        "id": "IN5431",
        "title": "IT and Management",
        "title_english": "IT and Management",
        "description": "The course covers the intersection of IT and management, including IT governance, digital strategy, and technology-driven organizational change.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "English",
        "exam_form": "Home exam", "teaching_form": "Lectures + seminars",
    },
    {
        "id": "IN5440",
        "title": "Selected topics in static analysis",
        "title_english": "Selected topics in static analysis",
        "description": "The course covers advanced techniques in static program analysis including abstract interpretation, type systems, and dataflow analysis.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "English",
        "exam_form": "Oral exam", "teaching_form": "Lectures + seminars",
    },
    {
        "id": "IN5450",
        "title": "Array Signal Processing",
        "title_english": "Array Signal Processing",
        "description": "The course covers signal processing techniques for sensor arrays including beamforming, direction-of-arrival estimation, and spatial filtering.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "English",
        "exam_form": "Written exam", "teaching_form": "Lectures + exercises",
    },
    {
        "id": "IN5460",
        "title": "Kunstig intelligens for energiinformatikk",
        "title_english": "AI for Energy Informatics",
        "description": "Emnet dekker bruk av AI-metoder for energisystemer, inkludert maskinlæring for lastprognoser, optimalisering og smarte energinett.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Prosjektoppgave", "teaching_form": "Forelesninger + lab",
    },
    {
        "id": "IN5490",
        "title": "Advanced Topics in Artificial Intelligence for Intelligent Systems",
        "title_english": "Advanced Topics in Artificial Intelligence for Intelligent Systems",
        "description": "The course explores contemporary methods in AI and machine learning including evolutionary computation, neural networks, and swarm intelligence, with applications in robotics, music, and healthcare.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "English",
        "exam_form": "Pass/fail: presentations + assignments", "teaching_form": "Forelesninger + workshops",
    },
    {
        "id": "IN5500",
        "title": "IT-støttet samarbeid",
        "title_english": "Computer-Supported Cooperative Work",
        "description": "Emnet dekker teorier og metoder for IT-støttet samarbeid (CSCW), inkludert groupware, samarbeidsverktøy og distribuert arbeid.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Hjemmeeksamen", "teaching_form": "Forelesninger + seminarer",
    },
    {
        "id": "IN5550",
        "title": "Neural Methods in Natural Language Processing",
        "title_english": "Neural Methods in Natural Language Processing",
        "description": "Advanced techniques in NLP with emphasis on deep learning and neural networks. Covers representation learning, document classification, sequence tagging, and natural language generation using FFNNs, CNNs, RNNs, and Transformers.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "English",
        "exam_form": "Project + report", "teaching_form": "Forelesninger + lab",
    },
    {
        "id": "IN5560",
        "title": "Datastyring",
        "title_english": "Data Governance",
        "description": "Emnet dekker prinsipper og praksis for datastyring, inkludert datakvalitet, personvern, compliance og dataarkitektur.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Hjemmeeksamen", "teaching_form": "Forelesninger + seminarer",
    },
    {
        "id": "IN5580",
        "title": "Computability theory",
        "title_english": "Computability Theory",
        "description": "The course covers advanced topics in computability theory including degrees of unsolvability, recursion theory, and the arithmetical hierarchy.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "English",
        "exam_form": "Oral exam", "teaching_form": "Lectures + exercises",
    },
    {
        "id": "IN5590",
        "title": "Hurtig modellframstilling av robotikksystemer",
        "title_english": "Rapid Prototyping of Robotic Systems",
        "description": "Emnet dekker metoder for rask prototyping og utvikling av robotsystemer, inkludert 3D-printing, sensorer og programvare.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "Norwegian",
        "exam_form": "Prosjektoppgave", "teaching_form": "Forelesninger + lab",
    },
    {
        "id": "IN5610",
        "title": "Advanced Topic in Digital Innovation",
        "title_english": "Advanced Topic in Digital Innovation",
        "description": "The course covers advanced topics in digital innovation, exploring how organizations create and capture value through digital technologies.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "English",
        "exam_form": "Home exam", "teaching_form": "Lectures + seminars",
    },
    {
        "id": "IN5620",
        "title": "Interaction with AI and autonomous systems",
        "title_english": "Interaction with AI and autonomous systems",
        "description": "The course explores human interaction with AI and autonomous systems, covering topics like explainable AI, trust, and human-AI collaboration.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "English",
        "exam_form": "Project + presentation", "teaching_form": "Lectures + workshops",
    },
    {
        "id": "IN5630",
        "title": "Programming Language Implementation and Formalisation",
        "title_english": "Programming Language Implementation and Formalisation",
        "description": "The course covers formal semantics and implementation techniques for programming languages, including type theory and proof assistants.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "English",
        "exam_form": "Written exam", "teaching_form": "Lectures + exercises",
    },
    {
        "id": "IN5700",
        "title": "Tåke og Sky Databehandling",
        "title_english": "Fog and Cloud Computing",
        "description": "Emnet gir grunnleggende kunnskap for å forstå utfordringer ved design av tåkedatasystemer og applikasjoner. Studentene lærer å spesifisere, designe, programmere, analysere og implementere slike systemer.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "English",
        "exam_form": "Gruppeprosjekt + muntlig eksamen", "teaching_form": "Forelesninger + lab",
    },
    {
        "id": "IN5800",
        "title": "Declarative Data Engineering",
        "title_english": "Declarative Data Engineering",
        "description": "Overview of data engineering focusing on data integration, abstraction, and aggregation through declarative methods and languages. Practical experience with mapping sources into common formats and managing complex metadata.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["spring"], "language": "English",
        "exam_form": "Gruppeprosjekt + muntlig presentasjon", "teaching_form": "Forelesninger + seminarer",
    },

    # ========== Niche/Special ==========
    {
        "id": "DIGHEL4350",
        "title": "Helsetjenester og informasjonsbehov",
        "title_english": "Health Services and Information Needs",
        "description": "Emnet utforsker informasjonsbehov i helsetjenesten og hvordan digitale systemer kan støtte klinisk beslutningstaking.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Hjemmeeksamen", "teaching_form": "Forelesninger + seminarer",
    },
    {
        "id": "DIGHEL4360",
        "title": "Informatikk for helsearbeidere",
        "title_english": "Informatics for Health Workers",
        "description": "Emnet gir helsearbeidere en innføring i informatikk med fokus på elektroniske pasientjournaler, helseinformatikk og digitale helseløsninger.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "master", "semester": ["fall"], "language": "Norwegian",
        "exam_form": "Hjemmeeksamen", "teaching_form": "Forelesninger + seminarer",
    },
    {
        "id": "SIFI2000",
        "title": "Foundations of Digitalization",
        "title_english": "Foundations of Digitalization",
        "description": "The course provides foundational knowledge about digitalization, covering key concepts, theories, and societal implications of digital transformation.",
        "credits": 10, "department": "Institutt for informatikk",
        "level": "bachelor", "semester": ["fall", "spring"], "language": "English",
        "exam_form": "Written exam", "teaching_form": "Lectures + seminars",
    },
    {
        "id": "SIFI2100",
        "title": "Programming: Principles and Practice",
        "title_english": "Programming: Principles and Practice",
        "description": "An introductory programming course covering fundamental principles and practical skills in software development.",
        "credits": 5, "department": "Institutt for informatikk",
        "level": "bachelor", "semester": ["spring"], "language": "English",
        "exam_form": "Written exam", "teaching_form": "Lectures + lab",
    },
    {
        "id": "SIFI2200",
        "title": "Digital Innovation",
        "title_english": "Digital Innovation",
        "description": "The course explores digital innovation processes, methods, and organizational implications.",
        "credits": 5, "department": "Institutt for informatikk",
        "level": "bachelor", "semester": ["spring"], "language": "English",
        "exam_form": "Project", "teaching_form": "Lectures + seminars",
    },
    {
        "id": "SIFI2300",
        "title": "Artificial Intelligence and Digitalization",
        "title_english": "Artificial Intelligence and Digitalization",
        "description": "The course provides an introduction to AI concepts and their role in digitalization, covering machine learning basics and ethical considerations.",
        "credits": 5, "department": "Institutt for informatikk",
        "level": "bachelor", "semester": ["spring"], "language": "English",
        "exam_form": "Written exam", "teaching_form": "Lectures + exercises",
    },
]


def main():
    db = SessionLocal()
    added = 0
    skipped = 0

    try:
        for course_data in NEW_COURSES:
            existing = db.query(Course).filter(Course.id == course_data["id"]).first()
            if existing:
                print(f"  SKIP {course_data['id']} - already exists")
                skipped += 1
                continue

            level_map = {"bachelor": CourseLevel.BACHELOR, "master": CourseLevel.MASTER, "phd": CourseLevel.PHD}
            semester_map = {"fall": "FALL", "spring": "SPRING"}

            course = Course(
                id=course_data["id"],
                title=course_data["title"],
                title_english=course_data.get("title_english"),
                description=course_data.get("description"),
                credits=course_data["credits"],
                department=course_data["department"],
                level=level_map[course_data["level"]],
                semester=[semester_map[s] for s in course_data["semester"]],
                language=course_data.get("language", "Norwegian"),
                exam_form=course_data.get("exam_form"),
                teaching_form=course_data.get("teaching_form"),
                is_active=True,
            )
            db.add(course)
            print(f"  ADD  {course_data['id']} - {course_data['title']}")
            added += 1

        db.commit()
        print(f"\nDone! Added {added} courses, skipped {skipped} existing.")
    except Exception as e:
        db.rollback()
        print(f"Error: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    main()
